steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/my-app-image", "."]

- name: "gcr.io/cloud-builders/gcloud"
  args: ["run", "deploy", "my-cloud-run-service", "--image", "gcr.io/$PROJECT_ID/my-app-image", "--platform", "managed", "--region", "us-central1"]
  args: ["config", "set", "api_endpoint_overrides/run", "https://us-central1-run.googleapis.com/"]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY
