version: '3.9'

services:
  app:
    container_name: audease-mvp-fe
    image: audease-mvp-fe
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 8080:8080
