name: Audease Deployment

on:
  pull_request:
    branches: ['main']

permissions:
  contents: read
  pull-requests: read

env:
  FORCE_COLOR: 3
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: npm

    - name: Install
      run: npm install

    - name: Run JS test
      run: npm run test

  push_to_github_registry:
    if: github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'
    needs: ['test']
    runs-on: ubuntu-latest

    # steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v4

    # - name: Log in to the Container registry
    #   uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
    #   with:
    #     registry: ${{ env.REGISTRY }}
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GHCR_TOKEN }}

    # - name: Extract metadata (tags, labels) for Docker
    #   id: meta
    #   uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
    #   with:
    #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    # - name: Build and push Docker image
    #   id: push
    #   uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}
